In [2]:
import numpy as np

In [5]:
obstacle = np.load("preprocessing/pysocialforce_obstacles_meter/00_Zurich_HB_anchored.npy")
print(obstacle)

[[  6.46999194   6.87436644 242.62469781 242.62469781]
 [  6.46999194   6.46999194 242.62469781 242.22032332]
 [  6.87436644   7.27874093 242.62469781 242.62469781]
 ...
 [243.4334468  243.8378213    0.4043745    0.4043745 ]
 [243.4334468  243.8378213    0.           0.        ]
 [243.8378213  243.8378213    0.4043745    0.        ]]


In [ ]:
# load npz file and print its content

# Load the npz file
data = np.load("sim/results/simulations/sim_00_Zurich_HB_1766256107.npz", allow_pickle=True)

# Print the keys in the npz file
print("Keys in the npz file:", list(data.keys()))

# Print the content of each array
for key in data.keys():
    print(f"Content of {key}:")
    print(data[key])

FileNotFoundError: [Errno 2] No such file or directory: 'preprocessing/pysocialforce_obstacles_meter/00_Zurich_HB_anchored.npy'